name: CI

on:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    # The type of runner that the job will run on


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            php-datatypes:
              - 'packages/php-datatypes/**'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  build_datatypes:
    runs-on: ubuntu-latest
    steps:
      - name: Changed datatypes
        if: jobs.build.steps.changes.outputs.php-datatypes == 'true'
        run: echo "datatypes changed"
